# Generated by Django 5.0.3 on 2024-05-27 16:00

import book.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default=book.models.default_image_path, null=True, upload_to='covers/')),
                ('year_published', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_stock', models.PositiveIntegerField(default=0)),
                ('available', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
