# Generated by Django 5.0.3 on 2024-05-12 09:37

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_available_book_total_stock_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default=book.models.default_image_path, null=True, upload_to='covers/'),
        ),
    ]
